version: '3.3'
services:
  valorsbotapi:
    image: valorsbotapi
    build: ./VALORS-Bot-API
    restart: always
    ports:
      - "9591:8080"
    environment:
      DATABASE_URL: postgresql+asyncpg://valorsuser:valorspassword@valorsdb:5432/valorsdb
      REDIS_HOST: valorscache
      REDIS_PORT: 6379
      LOG_LEVEL: 1
      PYTHONPATH: /srv
    volumes:
      - ./VALORS-Bot-API/app:/srv/app
      - ./VALORS-Bot-API/pipe:/hostpipe
      - /var/www/cdn:/cdn
  
  valorsbot:
    image: valorsbot
    build: ./bot
    restart: always
    environment:
      DATABASE_URL: postgresql+asyncpg://valorsuser:valorspassword@valorsdb:5432/valorsdb
      REDIS_HOST: valorscache
      REDIS_PORT: 6379
    depends_on:
      - valorsdb
    volumes:
      - ./bot/VALORS-Match-Making-Bot/alembic/versions:/bot/alembic/versions
  
  pmmcrossplay:
    image: pmmcrossplaybot
    build: ./crossplay
    restart: always
    depends_on:
      - pmmcrossplaydb
  
  valorsdb:
    image: postgres:latest
    container_name: valorsdb
    restart: always
    environment:
      POSTGRES_USER: valorsuser
      POSTGRES_PASSWORD: valorspassword
      POSTGRES_DB: valorsdb
    volumes:
      - ./db/ValorsDB:/var/lib/postgresql/data
  
  pmmcrossplaydb:
    image: pmmcrossplaydb
    build: ./Database
    env_file:
      - ./Database/gel.env
    volumes:
      - ./db/pmm:/var/lib/gel/data
      - ./Database/dbschema:/dbschema
    ports:
      - "9956:9956"
    restart: unless-stopped
  
  # devvalorsdb:
  #   image: postgres:latest
  #   container_name: devvalorsdb
  #   restart: always
  #   environment:
  #     POSTGRES_USER: valorsuser
  #     POSTGRES_PASSWORD: valorspassword
  #     POSTGRES_DB: valorsdb
  #   ports:
  #     - "5430:5432"
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_valors
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: projects@oblivius.dev
      PGADMIN_DEFAULT_PASSWORD: valorspassword
    ports:
      - "9592:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
  
  dozzle:
    image: amir20/dozzle:latest
    restart: always
    environment:
      DOZZLE_FILTER: name=valorsleague
      DOZZLE_AUTH_PROVIDER: simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle-data:/data
    ports:
      - 9593:8080
  
  valorscache:
    image: redis:latest
    restart: always
