version: '3.3'
services:
  valorsbotapi:
    image: valorsbotapi
    build: ./VALORS-Bot-API
    restart: always
    ports:
      - "9591:8080"
    environment:
      DATABASE_URL: postgresql+psycopg2://valorsuser:valorspassword@valorsdb:5432/valorsdb
      REDIS_HOST: valorscache
      REDIS_PORT: 6379
      LOG_LEVEL: 1
    volumes:
      - ./VALORS-Bot-API/pipe:/hostpipe
  
  valorsbot:
    image: valorsbot
    build: ./bot
    restart: always
    environment:
      DATABASE_URL: postgresql+asyncpg://valorsuser:valorspassword@valorsdb:5432/valorsdb
      REDIS_HOST: valorscache
      REDIS_PORT: 6379
    depends_on:
      - valorsdb
    volumes:
      - ./bot/VALORS-Match-Making-Bot/alembic/versions:/bot/alembic/versions
  
  valorsdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: valorsuser
      POSTGRES_PASSWORD: valorspassword
      POSTGRES_DB: valorsdb
    volumes:
      - ./db/ValorsDB:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_valors
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 99dark.oblivion99@gmail.com
      PGADMIN_DEFAULT_PASSWORD: valorspassword
    ports:
      - "9592:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
  
  dozzle:
    image: amir20/dozzle:latest
    restart: always
    environment:
      DOZZLE_FILTER: name=valorsleague
      DOZZLE_AUTH_PROVIDER: simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle-data:/data
    ports:
      - 9593:8080
  
  valorscache:
    image: redis:latest
    restart: always
